package com.sctrcd.busspassws.rules

import com.sctrcd.buspassws.facts.*;


declare IsAdult
	person: Person
end
declare IsChild
	person: Person
end

rule LeaderCheckRule when
    $c : CoreFact( ownerName == "Scott" && processDefinitionKey == "Inspect" && taskDefinitionKey == "LeaderCheck")
then
    restUtil.post("http://192.168.1.101:8080/notify/" + memberId, message);
    insertLogical(new LeaderCheck($c));
end

rule LeaderCheckPassRule when
	$l : LeaderCheck
	CoreFact(result == "pass")
then 
	restUtil.post("http://192.168.1.101:8080/notify/" + chiefId, message);
end

rule ChiefCheckRule when
    $c : CoreFact( ownerName == "Scott" && processDefinitionKey == "Inspect" && taskDefinitionKey == "ChiefCheck")
then
    restUtil.post("http://192.168.1.101:8080/notify/" + memberId, message);
    restUtil.post("http://192.168.1.101:8080/notify/" + leaderId, message);
end

rule IsAdultPolicy when
    p : Person( age >= 16 )
then
    insertLogical( new IsAdult( p ) );
end


rule IssueChildBusPass when
    p : Person()
    IsChild( person == p )
then
    insertLogical( new ChildBusPass( p ) );
end

rule IssueAdultBusPass when
    p : Person()
    IsAdult( person == p )
then
    insertLogical( new AdultBusPass( p ) );
end

function isTaskBeforeModified(targetTask, modifiedBpmnTask) {
	currentTask = targetTask;
	while (currentTask != null) {
		if (currentTask.bpmnTask().name != modifiedBpmnTask.name)
			currentTask = currentTask.lastTask();
		else 
			return false;
	}
	return true;
}

